import type { Metadata } from 'next'
import './globals.css'
import { Sora } from 'next/font/google'
import Header from "@/components/custom/header";
import Footer from "@/components/custom/footer";
import {FC} from "react";
import {ReactNode} from "react";

const sora = Sora({
  subsets: ['latin'],
  variable: '--font-inter',
})
export const metadata: Metadata = {
  title: 'Codery',
  description: 'Generated by create next app',
}

interface Props {
    children: ReactNode;
}

const RootLayout: FC<Props> = ({children}) => {

  return (
    <html  lang="en">
      <body className={sora.className}>
      <Header />
      {children}
      </body>
      <Footer />
    </html>
  )
}

export default RootLayout;


