import type { Metadata } from 'next'
import './globals.css'
import { Sora } from 'next/font/google'
import Header from "@/components/custom/header";
import Footer from "@/components/custom/footer";

const sora = Sora({
  subsets: ['latin'],
  variable: '--font-inter',
})
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const RootLayout = ({children}: {children: React.ReactNode}) => {
  return (
    <html  lang="en">
      <body className={sora.className}>
      <Header />
      {children}
      </body>
      <Footer />
    </html>
  )
}

export default RootLayout;


