import type { Metadata } from 'next'
import './globals.css'
import { Sora } from 'next/font/google'
import Header from "@/components/custom/header";
import Footer from "@/components/custom/footer";
import {FC} from "react";
import {ReactNode} from "react";
import { dir } from 'i18next'

import { languages } from '../i18n/settings'

export async function generateStaticParams() {
    return languages.map((lng) => ({ lng }))
}


const sora = Sora({
  subsets: ['latin'],
  variable: '--font-inter',
})
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

interface Props {
    children: ReactNode;
    params: {
        lng: string;
    }
}

const RootLayout: FC<Props> = ({children, params: { lng }}) => {
  return (
    <html  lang={lng} dir={dir(lng)}>
      <body className={sora.className}>
      <h1></h1>
      <Header />
      {children}
      </body>
      <Footer />
    </html>
  )
}

export default RootLayout;


